### ISSUE TITLE
Mapping Issue | Tiles in medbay lack atmospherics

### ISSUE THREAD

**Issue by ISOSS13** [Daelso/Warhammer-IS12#120]
Issue: Lack of pressure when standing in medbay doorway

Extraneous: Icy, the new host/owner told me in VC that the medbay doors lack atmospherics, this is likely because the tiles the doors are placed un use unsimulated turfs. Easy to check if this is the case, which it almost certainly is, even easier to fix (delete tiles and replace with normal ones, probably don't have to say this, but uh... you never know). I would do it but I'm busy, may get round to it if no one else does. If this is not the case, then I have no idea what could have caused it.

**Comment by reklaw9** [comment]
its the type of the tile in it
