### ISSUE TITLE
Tech priest "clothing" removable via acid

### ISSUE THREAD

**Issue by ISOSS13** [Daelso/Warhammer-IS12#121]
Issue:Tech priest clothes are not acid proof and can be removed with sulphuric acid, this is not intended and a simple fix would be adding an acid proof tag or resistance X or whatever.

**Comment by reklaw9** [comment]
biologis don't even have their own clothing, they only have a FAKE tech priest hoodie and no cybernetic upgrades

**Comment by Daelso** [comment]
fixed
