### ISSUE TITLE
cryotubes prevent respawn

### ISSUE THREAD

**Issue by th6795** [Daelso/Warhammer-IS12#93]
verify & fix: being cryo tubed prevents respawning

fix: simplest fix is probably to temporarily disable the functionality of cryotubes- a better fix would be to allow cryo'd people to respawn, however need to prevent people from just cryo tubing to hop roles

**Comment by WageCrusader** [comment]
Wouldn't a better approach just be to remove whoever is cryo'd from the round, like on Baystation? I don't see any possible way to prevent people from abusing that to hop roles
