### ISSUE TITLE
investigate & balance pain

### ISSUE THREAD

**Issue by th6795** [Daelso/Warhammer-IS12#95]
many complaints of pain being too high- needs investigation and tweaking if it's unreasonable

**Comment by Mw1113** [comment]
Currently Investigating 

-Clarke

**Comment by reklaw9** [comment]
it isn't, simple as that

**Comment by Mw1113** [comment]
> it isn't, simple as that

Who are you who are so wise in the ways of BYOND?

**Comment by reklaw9** [comment]
A guy that has been playing SS13 for too long.
1010000 1110010 1100001 1101001 1110011 1100101 100000 1110100 1101000 1100101 100000 1001111 1101101 1101110 1101001 1110011 1110011 1101001 1100001 1101000 101110

Brute damage pain shouldn't be changed at all. but BURN DAMAGE PAIN is coded in to give EXTRA pain.
Go to the following to change how much pain damage gives(SHOULD be the following line, but im not really a good coder sooo...):
line 131 in:
Warhammer-IS12/code/modules/organs/external/_external_damage.dm

> > it isn't, simple as that
> 
> Who are you who are so wise in the ways of BYOND?
